#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import numpy as np
import pandas as pd
import pandas_datareader as web
from datetime import datetime
from datetime import date


# In[ ]:


today = date.today()
data = web.DataReader('^GSPC', data_source = 'yahoo', start = '1/1/2008', end = today)
data.info()


# In[ ]:


path = r'C:\Users\Nick\Desktop'
name = r'\ts_data'
date = datetime.now().strftime("%d-%m-%Y_%I-%M-%S_%p")
filetype = '.csv'
data.to_csv(path+name+date+filetype)


# In[ ]:


data['Close'].plot(grid=True, figsize=(15,9))


# In[ ]:


data['42d']=np.round(data['Close'].rolling(window=42).mean(),2)
data['252d']=np.round(data['Close'].rolling(window=252).mean(),2)
data[['Close', '42d', '252d']].tail()


# In[ ]:


data[['Close', '42d', '252d']].plot(grid=True, figsize=(15,9))


# #### Rule Based Triggers:
# 
# - ****Buy Signal (go long)**** 
#     - The 42d trend is for the first time SD points aove the 252d trend
#     
# - ****Wait (park in cash)****
#     - The 42d trend is within range of +/-SD points around the 252d trend
#   
# - ****Buy Signal (go short)****
#     - the 42d trend is for the first time SD points below the 252d trend

# In[ ]:


data['42-252'] = data['42d'] - data['252d']
data['42-252'].tail()


# In[ ]:


data['42-252'].head()


# In[ ]:


SD = 50
data['Regime'] = np.where(data['42-252'] > SD, 1, 0)
data['Regime'] = np.where(data['42-252'] < -SD, -1, data['Regime'])
data['Regime'].value_counts()


# In[ ]:


from matplotlib import pyplot as plt
data['Regime'].plot(lw = 1.5, figsize=(15,9))
plt.ylim([-1.1, 1.1])


# In[ ]:


data['Market'] = np.log(data['Close'] / data['Close'].shift(1))
data['Strategy'] = data['Regime'].shift(1) * data['Market']
data[['Market', 'Strategy']].cumsum().apply(np.exp).plot(grid = True, figsize=(15,9))
